package config

const USER_NAME = "user_name"
const USER_FIRST_NAME = "first_name"
const USER_LAST_NAME = "last_name"
const USER_EMAIL = "email"
const USER_MOBILE_NUMBER = "mobile_number"
const USER_DATE_OF_BIRTH = "date_of_birth"
const USER_PASSWORD = "password"
const USER_CONFIRM_PASSWORD = "confirm_password"

const ADDRESS_STREET = "street"
const ADDRESS_CITY = "city"
const ADDRESS_STATE = "state"
const ADDRESS_POSTAL_CODE = "postal_code"
const ADDRESS_COUNTRY = "country"

const TOKEN_EMAIL = "email"
const TOKEN_EXPIRATION = "exp"

const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET"
const CREDENTIAL_ENCRYPTION_KEY = "CREDENTIAL_ENCRYPTION_KEY"

const PAN_DETAILS = "pan_details"
const PAN_ID = "id"
const PAN_NUMBER = "pan_number"
const PAN_ISSUE_DATE = "issue_date"
const PAN_PASSWORD = "password"

const AADHAAR_NUMBER = "aadhaar_number"
const AADHAAR_ISSUE_DATE = "issue_date"
const AADHAAR_ID = "id"
const AADHAAR_DETAILS = "aadhaar_details"

const PRAN_NUMBER = "pran_number"
const PRAN_PASSWORD = "password"
const PRAN_ID = "id"
const PRAN_DETAILS = "pran_details"

const PASSPORT_NUMBER = "passport_number"
const PASSPORT_ISSUE_DATE = "issue_date"
const PASSPORT_EXPIRY_DATE = "expiry_date"
const PASSPORT_ISSUER_COUNTRY = "issuer_country"
const PASSPORT_USER_ID = "user_id"
const PASSPORT_PASSWORD = "password"
const PASSPORT_ID = "id"
const PASSPORT_DETAILS = "passport_details"

const IRCTC_DETAILS = "irctc_details"
const IRCTC_ID = "id"
const IRCTC_USER_NAME = "user_name"
const IRCTC_EMAIL_ID = "email_id"
const IRCTC_PASSWORD = "password"

const EMAIL_ID = "email_id"
const EMAIL_PASSWORD = "password"
const EMAIL_ENTITY = "entity"
const EMAIL_CONSTANT_ID = "id"
const EMAIL_DETAILS = "emails"

const MUTUAL_FUND_NAME = "fund_name"
const MUTUAL_FUND_FOLIO_NUMBER = "folio_number"
const MUTUAL_FUND_USER_ID = "user_id"
const MUTUAL_FUND_LOGIN_PASSWORD = "login_password"
const MUTUAL_FUND_TRANSACTION_PASSWORD = "transaction_password"
const MUTUAL_FUND_ID = "id"
const MUTUAL_FUND_MPIN = "mpin"
const MUTUAL_FUND_MOBILE_NUMBER = "mobile_number"
const MUTUAL_FUND_EMAIL_ID = "email_id"
const MUTUAL_FUND_DETAILS = "mutual_funds"

const BANK_ID = "id"
const BANK_USER_ID = "user_id"
const BANK_CUSTOMER_ID = "customer_id"
const BANK_NAME = "bank_name"
const BANK_LOGIN_PASSWORD = "login_password"
const BANK_TRANSACTION_PASSWORD = "transaction_password"
const BANK_MOBILE_PIN = "mobile_login_pin"
const BANK_MOBILE_TRANSACTION_PIN = "mobile_transaction_pin"
const BANK_DETAILS = "bank_details"

const MISC_TYPE_CODE = "type_code"
const MISC_DESCRIPTION = "description"
const MISC_KEY_1 = "key_1"
const MISC_VAL_1 = "val_1"
const MISC_KEY_2 = "key_2"
const MISC_VAL_2 = "val_2"
const MISC_ID = "id"
const MISC_DETAILS = "misc_details"
